### ISSUE TITLE
Creation Details for Label Shift

### ISSUE THREAD

**Issue by huang123ying** [xiangdal/implicit_alignment#2]

**Comment by xiangjjj** [comment]
If you are asking for the office-home dataset, you can download it from google drive https://drive.google.com/file/d/0B81rNlvomiwed0V1YUxQdC1uOTg/view. I've also uploaded it to BaiduNetDisk https://pan.baidu.com/s/1XEzXOBECxV5_x6LnwbrNHw  (extraction code: qvq6) if you can't access google drive.

**Comment by huang123ying** [comment]
thanks! I have downloaded it from google drive.
 Do you evaluate your model with Digits dataset?

**Comment by xiangjjj** [comment]
In our paper, we evaluated MNIST<->SVHN in section 4.4.4 under a simulated class distribution shift. The intention is to show implicit alignment can help improve DANN under class distribution shift; therefore, we didn't experiment with other domain adaptation techniques for digits. We have not evaluated the standard digits dataset.
The code for the digits experiments is in a private repo, as the data preprocessing pipeline is quite different from other datasets.

**Comment by huang123ying** [comment]
I am interested in the creation details for label shift and imbalance, so can you send me the unbalanced label files for Digits dataset? thanks!

**Comment by xiangjjj** [comment]
I see. For the Office-Home-RS-UT, it was created in COAL using a Pareto distribution.

For the digits dataset, I used a Pareto distribution to simulate extreme imbalance and a triangle-like distribution to simulate mild imbalance. It was implemented by putting a wrapper around the digits dataset in pytorch. I will release the dataset wrapper for my digits dataset before the next Monday, August 17th. (It needs a bit refactoring.)

**Comment by xiangjjj** [comment]
Hi, I've just uploaded two files:
- [digits.py](https://github.com/xiangdal/implicit_alignment/blob/master/ai/domain_adaptation/datasets/digits.py) creates unbalanced MNIST and SVHN datasets. You can use `unbalance_type` to config the datasets.
- [digit_stats.ipynb](https://github.com/xiangdal/implicit_alignment/blob/master/ai/domain_adaptation/datasets/digit_stats.ipynb) shows how the specific split is created from (i) linear-like and (ii) Pareto distributions.

**Comment by HESTIA00** [comment]
hi,Can you tell me where the code for the COAL model is? I have been learning this model recently
